name: Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:

      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display version
        run: |
          python -c "import sys; print(sys.version)"
          ls
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
          pipenv sync
      - name: Running tests
        run: |
          cd tests
          python -m unittest discover -t ../
          cd ../
          coverage report
      - name: mypy
        run: |
          mypy easystore
